### ISSUE TITLE
Is defaultHandler really necessary?

### ISSUE THREAD

**Issue by oscarotero** [middlewares/base-path-router#3]
I just realized that defaultHandler is the same than just adding a `/` route. For example:

```php
$middlewares[] = new Middlewares\BasePathRouter([
    '/admin' => $admin,
    '/admin/login' => $adminLogin,
    '/blog' => $blog,
    '/' => $defaultHandler
]);
```

If so, we could remove this option. Am I wrong?

**Comment by franzliedke** [comment]
That's probably true, yeah. It does feel a bit more expressive (especially when used for a `404` fallback), but I'd rather remove that than the `/` prefix.

Reason: I am essentially doing the following in Flarum:

~~~php
new Middlewares\BasePathRouter([
    path('admin') => 'middleware.admin',
    path('forum') => 'middleware.forum',
    path('api') => 'middleware.api',
]);
~~~

`path()` returns a prefix for that section of the app - for `forum`, it usually returns `/`, but this could be changed to something like `talk`. In that case (and I don't know when I need that case, because the prefix is dynamic), an explicit default handler would be nice. So I guess they are slightly different. :confused:

**Comment by oscarotero** [comment]
What do you mean with "the prefix is dynamic"?

**Comment by franzliedke** [comment]
It is dynamic because it is calculated by the `path()` function. With a static value, I would know that I have a fallback handler (I either have `/` or I don't). But with a dynamic value, I *sometimes* need one, and I don't want to start investigating those dynamic prefixes to determine whether I need one. So, to me, at that point, `defaultHandler` is still useful. Except if we had middlewares/request-handler#9, of course. :wink:

**Comment by oscarotero** [comment]
What I mean is whether the prefix can change or, once the forum is installed, is always the same. I'm asking this because there's the middlewares/base-path that could remove the common and unused base path. For example:

```php
$middlewares[] = new Middlewares\BasePath(path('/'));
$middlewares[] = new Middlewares\BasePathRouter([
    '/admin' => 'middleware.admin',
    '/api' => 'middleware.api',
    '/' => 'middleware.forum'
]);
```

**Comment by franzliedke** [comment]
It could definitely be changed by users / extensions.

**Comment by oscarotero** [comment]
I can add a `continueOnEmpty()` option to request-handler, [as described here](https://github.com/middlewares/request-handler/issues/9#issuecomment-415303399). Does this cover your use case?

**Comment by franzliedke** [comment]
Sounds perfect. So if we get middlewares/request-handler#9, I have nothing against removing the `defaultHandler` here.

**Comment by oscarotero** [comment]
Great. I'll work on that.

**Comment by oscarotero** [comment]
Ok, I've released a new version of middlewares/request-handler, removed the `defaultHandler` here and  added the `continueOnError` option to prevent returning the 404 response. Let me know if it's ok so we can tag a new version.

**Comment by franzliedke** [comment]
Perfect! :raised_hands:  Can you take care of the release?

**Comment by oscarotero** [comment]
Yes, no problem

**Comment by oscarotero** [comment]
v1.0.0 released. (I think this package is mature enough to swich to 1.x)
